name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn install --ignore-engines
    - run: yarn build
    - run: yarn lint

  test:

    runs-on: "${{matrix.os}}-latest"

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x, 15.x]
        os: ['ubuntu', 'windows']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --ignore-engines
    - run: yarn build
    - run: yarn test:unit
